export const thrashPath: string = '/assets/icons/thrash.svg'
export const editPath: string = '/assets/icons/edit.svg'
export const plusPath: string = '/assets/icons/plus.svg'
export const datePath: string = '/assets/icons/date.svg'
export const userBadgePath: string = '/assets/icons/user-badge.svg'
export const timePath: string = '/assets/icons/time.svg'
export const sharePath: string = '/assets/icons/share.svg'
export const peoplePath: string = '/assets/icons/people.svg'